import { StyleSheet } from "@react-pdf/renderer";

export const pdfColors = {
  teal: "#5CB8B2",
  tealDark: "#3D9A94",
  white: "#FFFFFF",
  text: "#1E293B",
  textMuted: "#64748B",
  border: "#CBD5E1",
  bgLight: "#F8FAFC",
};

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 28,
    paddingBottom: 36,
    paddingHorizontal: 32,
    fontSize: 9,
    fontFamily: "Helvetica",
    color: pdfColors.text,
    backgroundColor: pdfColors.white,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    minHeight: 76,
  },
  headerLogoBox: {
    flex: 1.4,
    justifyContent: "center",
    paddingRight: 14,
  },
  logo: {
    width: 300,
    height: 72,
    objectFit: "contain" as const,
  },
  headerBanner: {
    backgroundColor: pdfColors.teal,
    paddingVertical: 14,
    paddingHorizontal: 16,
    justifyContent: "center",
    alignItems: "center",
    minWidth: 170,
    maxWidth: 200,
  },
  headerBannerText: {
    color: pdfColors.white,
    fontSize: 13,
    fontWeight: "bold",
    letterSpacing: 0.5,
    textAlign: "center",
  },
  headerBannerSub: {
    color: pdfColors.white,
    fontSize: 8,
    marginTop: 2,
    textAlign: "center",
  },
  partiesRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 14,
  },
  partyBox: {
    flex: 1,
    border: `1pt solid ${pdfColors.border}`,
  },
  partyHeader: {
    backgroundColor: pdfColors.teal,
    paddingVertical: 5,
    paddingHorizontal: 8,
  },
  partyHeaderText: {
    color: pdfColors.white,
    fontSize: 8,
    fontWeight: "bold",
  },
  partyBody: {
    padding: 8,
    minHeight: 52,
  },
  partyName: {
    fontSize: 9,
    fontWeight: "bold",
    marginBottom: 3,
  },
  partyLine: {
    fontSize: 8,
    color: pdfColors.textMuted,
    marginBottom: 2,
    lineHeight: 1.35,
  },
  sectionBanner: {
    backgroundColor: pdfColors.teal,
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginTop: 10,
    marginBottom: 8,
  },
  sectionBannerText: {
    color: pdfColors.white,
    fontSize: 9,
    fontWeight: "bold",
    letterSpacing: 0.3,
  },
  introText: {
    fontSize: 8.5,
    color: pdfColors.textMuted,
    marginBottom: 8,
    lineHeight: 1.4,
  },
  table: {
    border: `1pt solid ${pdfColors.border}`,
    marginBottom: 6,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: pdfColors.bgLight,
    borderBottom: `1pt solid ${pdfColors.border}`,
  },
  tableHeaderCell: {
    paddingVertical: 5,
    paddingHorizontal: 8,
    fontSize: 8,
    fontWeight: "bold",
    color: pdfColors.text,
  },
  tableRow: {
    flexDirection: "row",
    borderBottom: `1pt solid ${pdfColors.border}`,
  },
  tableCell: {
    paddingVertical: 6,
    paddingHorizontal: 8,
    fontSize: 8,
    lineHeight: 1.35,
  },
  colService: { flex: 2 },
  colTechnique: { flex: 3, borderLeft: `1pt solid ${pdfColors.border}` },
  colQty: { flex: 0.6, textAlign: "center" },
  colUnit: { flex: 1, textAlign: "right" },
  colTotal: { flex: 1, textAlign: "right" },
  resultGroupTitle: {
    fontSize: 10,
    fontWeight: "bold",
    textAlign: "center",
    marginTop: 10,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  photoGrid: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 14,
    justifyContent: "center",
  },
  photoCol: {
    flex: 1,
    alignItems: "center",
    maxWidth: 240,
  },
  photoLabel: {
    fontSize: 9,
    fontWeight: "bold",
    marginBottom: 4,
    textAlign: "center",
  },
  photoHorizontal: {
    width: 220,
    height: 165,
    objectFit: "cover" as const,
    border: `1pt solid ${pdfColors.border}`,
  },
  photoVertical: {
    width: 130,
    height: 195,
    objectFit: "cover" as const,
    border: `1pt solid ${pdfColors.border}`,
  },
  photoPlaceholder: {
    width: 220,
    height: 120,
    border: `1pt dashed ${pdfColors.border}`,
    backgroundColor: pdfColors.bgLight,
    justifyContent: "center",
    alignItems: "center",
  },
  photoPlaceholderText: {
    fontSize: 8,
    color: pdfColors.textMuted,
  },
  metaRow: {
    flexDirection: "row",
    gap: 16,
    marginBottom: 8,
  },
  metaItem: {
    flexDirection: "row",
    gap: 4,
  },
  metaLabel: {
    fontSize: 8,
    fontWeight: "bold",
    color: pdfColors.textMuted,
  },
  metaValue: {
    fontSize: 8,
  },
  totalsBox: {
    marginTop: 12,
    alignSelf: "flex-end",
    width: 220,
    border: `1pt solid ${pdfColors.border}`,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderBottom: `1pt solid ${pdfColors.border}`,
  },
  totalRowFinal: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 7,
    paddingHorizontal: 10,
    backgroundColor: pdfColors.teal,
  },
  totalLabel: { fontSize: 8.5 },
  totalValue: { fontSize: 8.5 },
  totalFinalLabel: {
    fontSize: 10,
    fontWeight: "bold",
    color: pdfColors.white,
  },
  totalFinalValue: {
    fontSize: 10,
    fontWeight: "bold",
    color: pdfColors.white,
  },
  infoBlock: {
    marginTop: 10,
    padding: 8,
    border: `1pt solid ${pdfColors.border}`,
    backgroundColor: pdfColors.bgLight,
  },
  infoBlockTitle: {
    fontSize: 8,
    fontWeight: "bold",
    marginBottom: 4,
  },
  infoBlockText: {
    fontSize: 8,
    lineHeight: 1.4,
  },
  signatureRow: {
    flexDirection: "row",
    gap: 24,
    marginTop: 20,
    paddingTop: 12,
  },
  signatureBox: {
    flex: 1,
    alignItems: "center",
  },
  signatureSpace: {
    width: "100%",
    height: 68,
    justifyContent: "flex-end",
    alignItems: "center",
    marginBottom: 4,
  },
  signatureImage: {
    width: 180,
    height: 60,
    objectFit: "contain" as const,
  },
  signatureLine: {
    borderTop: `1pt solid ${pdfColors.text}`,
    width: "100%",
    paddingTop: 6,
    alignItems: "center",
  },
  signatureTitle: {
    fontSize: 8,
    fontWeight: "bold",
    textAlign: "center",
  },
  signatureSubtitle: {
    fontSize: 7.5,
    color: pdfColors.textMuted,
    textAlign: "center",
    marginTop: 2,
    fontStyle: "italic",
  },
  footerNote: {
    marginTop: 14,
    fontSize: 7,
    color: pdfColors.textMuted,
    textAlign: "center",
  },
  acceptanceBox: {
    marginTop: 16,
    padding: 10,
    border: `1pt solid ${pdfColors.border}`,
  },
  acceptanceText: {
    fontSize: 8,
    marginBottom: 8,
    lineHeight: 1.4,
  },
  acceptanceSignatureSpace: {
    height: 56,
    width: "65%",
    alignSelf: "center",
  },
  acceptanceLine: {
    borderTop: `1pt solid ${pdfColors.text}`,
    width: "60%",
    alignSelf: "center",
    paddingTop: 4,
  },
  acceptanceLabel: {
    fontSize: 7.5,
    textAlign: "center",
    color: pdfColors.textMuted,
    marginTop: 2,
  },
});
